# This workflow will install the python package and dependencies, and run tests against a variety of Python versions

name: test-latex

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * *"  # Every day at 1pm UTC (6am PST)

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install .
        python -m pip install pytest
        sudo apt-get install texlive texlive-latex-extra latexmk poppler-utils
        mkdir -p ~/texmf/tex/latex
        wget http://mirrors.ctan.org/graphics/pgf/contrib/quantikz/tikzlibraryquantikz.code.tex -P ~/texmf/tex/latex
    - name: About
      run: |
        python -m $(python -Wi setup.py --name).about
        echo
        pdflatex --version
        pdftocairo -v
    - name: Test with pytest
      run: |
        python -m pytest

